= Quarkus AdminFaces extension
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://travis-ci.org/rmpestano/quarkus-omnifaces.svg[Build Status (Travis CI), link=https://travis-ci.org/adminfaces/quarkus-adminfaces]

Enables AdminFaces, OmniFaces and PrimeFaces Extensions in Quarkus applications

 
This projects is based on https://github.com/rmpestano/quarkus-omnifaces[OmniFaces Extension^] and adds AdminFaces and PrimeFaces Extension support in native mode


== Usage

Add the extension in your quarkus project:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-adminfaces</artifactId>
    <version>${quarkus.version}</version>
</dependency>
```
== Run sample application

* `cd system-tests && mvn compile quarkus:dev`
* access http://localhost:8080/

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-adminfaces-st-runner.jar`

== Native mode

To run o quarkus native use:

`mvn clean package -Pnative && ./target/quarkus-adminfaces-st-runner`

== Run System tests

`mvn clean test`

=== Run native tests

`mvn verify -Pnative`


== Other examples

https://github.com/adminfaces/quarkus-admin-starter[Quarkus admin starter^] and https://github.com/adminfaces/quarkus-admin-showcase[Quarkus admin showcase^] are more elaborated applications using quarkus-omnifaces and quarkus myfaces extension. Follow the instructions on readme in order to run them.

